repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
        files: \.py$
    -   id: trailing-whitespace
        files: \.py$
    -   id: check-ast
        files: \.py$
    -   id: check-builtin-literals
        files: \.py$
    -   id: check-docstring-first
        files: \.py$
    -   id: check-case-conflict
        files: \.py$
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch=master, --branch=release]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.2'
    hooks:
      - id: autopep8
        args: [--in-place, --max-line-length=120, --ignore=E203]
        exclude: |
          (?x)^(
              vr\/src\/rnd\/.*|
              ci\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: |
          (?x)^(
              vr\/src\/rnd\/.*|
              ci\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black", "--skip", "__init__.py", "--filter-files"]
        exclude: |
          (?x)^(
              vr\/src\/rnd\/.*|
              ci\/.*|
              delete-this-string-after-end-integration\/.*
          )$
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=W503,W504,E302,E203']
        exclude: |
          (?x)^(
              vr\/src\/rnd\/.*|
              ci\/.*|
              delete-this-string-after-end-integration\/.*
          )$
